# -*- coding: utf-8 -*-
"""detroit_menu.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X755KdxWBrDW4Zru9zrhisTlI658NGU5
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd

# Lista de páginas do cardápio (Cada uma representa uma categoria)
urls = ['https://detroitsteakhouse.com.br/cardapio-digital/favorities/',
        'https://detroitsteakhouse.com.br/cardapio-digital/burgers-milkshakes/',
        'https://detroitsteakhouse.com.br/cardapio-digital/appetizers/' ]

# Lista onde os dados serão armazenados
lista = []

for url in urls:
  response = requests.get(url) # Faz a requisição HTTP para acessar a pagina
  soup = BeautifulSoup(response.text, 'html.parser') # Converte o HTML em objeto navegavel
  itens = soup.find_all(class_='box-produto-lista') # Busca todos os produtos da página
  for item in itens:
    nome = item.find(class_='mt-0') # Localiza o nome
    nome = nome.text.strip()        # Remove os espaços extras
    preco = item.find(class_='precos') # Localiza o preço
    if preco:                          # Verifica se o preço existe
      preco = preco.text               # Extrai o texto bruto
      preco = preco.split('\n')        # Remove quebra de lihas e pega primeira parte
      preco = preco[0]
      preco = preco.split('|')
      preco = preco[0]
      preco = preco.replace(',', '.').replace('R$', '').split(' ') # Remove símbolos e separa os valores
      preco_final = None
      for parte in preco:    # Percorre cadca parte tentado converte para número
        try:
          numero = float(parte)  # Tenta converter
          preco_final = numero  # Se der certo, salva
        except:
          pass        # Ignora valores inválidos

    lista.append({'restaurante':'Detroit',      # Nome fixo do restaurante
                  'product_name': nome,         # Nome do produto
                  'preco': preco_final})        # Preço tratado


df.to_csv('detroit_menu_clean.csv', index=False, encoding ='utf-8-sig')